In [56]:
import numpy as np
import numpy.linalg as LA
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
coloredpics = np.arange(48).reshape(4,4,3)
coloredpics

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]]])

In [9]:
coloredpics.sum(axis=0) #eliminating that dimension by summing along it

array([[ 72,  76,  80],
       [ 84,  88,  92],
       [ 96, 100, 104],
       [108, 112, 116]])

In [7]:
coloredpics.sum(axis=1)

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122],
       [162, 166, 170]])

In [8]:
coloredpics.sum(axis=2)

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102],
       [111, 120, 129, 138]])

In [10]:
coloredpics.sum(axis=2)/3

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

In [28]:
array = np.arange(16).reshape(4,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
squarer = lambda t: t ** 2
rooter = lambda t: t ** 0.5

In [16]:
array2 = np.array([squarer(xi) for xi in array])

In [17]:
array2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [33]:
array = np.array([rooter(xi) for xi in array])
array

array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.]])

In [32]:
array = np.array([squarer(xi) for xi in array])
array

array([[0.0000e+00, 1.0000e+00, 1.6000e+01, 8.1000e+01],
       [2.5600e+02, 6.2500e+02, 1.2960e+03, 2.4010e+03],
       [4.0960e+03, 6.5610e+03, 1.0000e+04, 1.4641e+04],
       [2.0736e+04, 2.8561e+04, 3.8416e+04, 5.0625e+04]])

In [35]:
foo = np.arange(25)

In [37]:
divisibleby = filter(lambda x: x%3 == 0, foo)
print(list(divisibleby))

[0, 3, 6, 9, 12, 15, 18, 21, 24]


In [40]:
lambda_map =  map(lambda x:x*2 + 10, foo)

In [41]:
lambda_map

[10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58]

In [51]:
listl = ['A', 'B','C', 'D','E','F']
c = 0
for letter1 in listl:
    for letter2  in listl:
        c=c+1
        print(str(c)+': '+letter1+letter2)


1: AA
2: AB
3: AC
4: AD
5: AE
6: AF
7: BA
8: BB
9: BC
10: BD
11: BE
12: BF
13: CA
14: CB
15: CC
16: CD
17: CE
18: CF
19: DA
20: DB
21: DC
22: DD
23: DE
24: DF
25: EA
26: EB
27: EC
28: ED
29: EE
30: EF
31: FA
32: FB
33: FC
34: FD
35: FE
36: FF


In [49]:
[i*i for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [52]:
!ls -l

total 192
-rw-r--r--@ 1 satyajeetpradhan  staff     20 Nov 20 19:58 README.md
-rw-r--r--  1 satyajeetpradhan  staff   5470 Nov 13 22:49 Session 2 - October 14.ipynb
-rw-r--r--  1 satyajeetpradhan  staff   1002 Nov 13 23:21 Session 3 - October 27.ipynb
-rw-r--r--  1 satyajeetpradhan  staff   3343 Nov 20 20:29 Session 4 - October 28.ipynb
-rw-r--r--  1 satyajeetpradhan  staff  18203 Nov 20 21:37 Session 5 - November 03.ipynb
-rw-r--r--  1 satyajeetpradhan  staff   2894 Nov 20 23:22 Session 6.ipynb
-rw-r--r--  1 satyajeetpradhan  staff  26138 Nov 28 23:42 Session 7 - November 10.ipynb
-rw-r--r--  1 satyajeetpradhan  staff   8660 Nov 30 02:12 Session 8- November 17.ipynb
-rw-r--r--  1 satyajeetpradhan  staff   9422 Nov 20 23:47 Session6 Part 2 Numpy Nov 04th.ipynb
drwxr-xr-x  9 satyajeetpradhan  staff    288 Nov 28 20:02 ml


In [57]:
help(LA)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

FILE
    /anaconda2/lib/python2.7/site-packages/numpy/linalg/__init__.py

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR dec