In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
b = np.array((3,4,5))

In [7]:
b

array([3, 4, 5])

In [8]:
type(b)

numpy.ndarray

In [13]:
x = np.zeros((2,3,4))
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
x = np.ones((3,4), dtype=np.float32)

In [18]:
np.full((3,4),.11)

array([[0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11]])

In [19]:
np.full((3,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [20]:
print(x.dtype)

float32


In [23]:
np.arange(10,30,2) #Creates an array of numbers between 10 to 30 with step 3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [24]:
x = [
        [
            1,2,3,4 
        ],
        [
            1,2,2,2
        ]
]

In [25]:
x

[[1, 2, 3, 4], [1, 2, 2, 2]]

In [27]:
%timeit x

10000000 loops, best of 3: 81.7 ns per loop


In [30]:
np.linspace(0,10,3)  # creates three numbers linearly spaced equallyfrom each other between 0 and 10

array([ 0.,  5., 10.])

In [31]:
np.random.rand(2,3)

array([[0.95751996, 0.24598624, 0.78265894],
       [0.9628362 , 0.25257541, 0.57665626]])

In [32]:
x = np.empty((2,3))

In [33]:
x.ndim

2

In [35]:
x.shape

(2, 3)

In [36]:
x

array([[0.95751996, 0.24598624, 0.78265894],
       [0.9628362 , 0.25257541, 0.57665626]])

In [48]:
b = x.reshape(-2)

In [46]:
b

array([0.95751996, 0.24598624, 0.78265894, 0.9628362 , 0.25257541,
       0.57665626])

In [49]:
b

array([0.95751996, 0.24598624, 0.78265894, 0.9628362 , 0.25257541,
       0.57665626])

In [50]:
b.reshape(3,2)

array([[0.95751996, 0.24598624],
       [0.78265894, 0.9628362 ],
       [0.25257541, 0.57665626]])

In [51]:
b

array([0.95751996, 0.24598624, 0.78265894, 0.9628362 , 0.25257541,
       0.57665626])

In [52]:
slice = b[2:6].copy()

In [53]:
slice

array([0.78265894, 0.9628362 , 0.25257541, 0.57665626])