# NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a.ndim

1

In [4]:
type(a)

numpy.ndarray

In [5]:
b = np.array((3,4,5))

In [6]:
b

array([3, 4, 5])

In [7]:
type(b)

numpy.ndarray

In [8]:
# Three dimensional array
x = np.zeros((2,3,4))
print(x)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [9]:
x.shape

(2, 3, 4)

In [10]:
y = np.ones((3,4), dtype=np.float64)

In [11]:
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
print(x.dtype)

float64


In [13]:
print(y.dtype)

float64


In [16]:
np.full((3,4), 0.11)

array([[0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11]])

In [17]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [20]:
np.arange(10,30,2) # Creates an array with step 2 increment

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [24]:
%timeit np.arange(1,100,0.0001) # %timeit to record time taken for operation

The slowest run took 6.27 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 581 µs per loop


In [25]:
np.arange(1,100,0.0001).shape

(990000,)

In [33]:
three_d_array = np.full((2,3,4),0.11)
print(three_d_array)

[[[0.11 0.11 0.11 0.11]
  [0.11 0.11 0.11 0.11]
  [0.11 0.11 0.11 0.11]]

 [[0.11 0.11 0.11 0.11]
  [0.11 0.11 0.11 0.11]
  [0.11 0.11 0.11 0.11]]]


In [27]:
print(three_d_array.size)
print(three_d_array.shape)

24
(2, 3, 4)


In [30]:
three_d_array.reshape(4,6)

array([[0.11, 0.11, 0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11, 0.11, 0.11],
       [0.11, 0.11, 0.11, 0.11, 0.11, 0.11]])

In [31]:
print(three_d_array.size)
print(three_d_array.shape)

24
(2, 3, 4)


In [34]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [35]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [41]:
x = np.random.rand(2,3)
print(x)

[[0.16763264 0.42135918 0.90015023]
 [0.76085709 0.78110816 0.7181189 ]]


In [42]:
x*9 + 1

array([[2.50869377, 4.79223259, 9.10135208],
       [7.84771383, 8.02997344, 7.46307011]])

In [43]:
a = np.array([1,5,3,19,13,7,3])
a[1]

5

In [44]:
a[2:5]

array([ 3, 19, 13])

In [45]:
a[:10:2]

array([ 1,  3, 13,  3])