# Linear Algebra

In [2]:
import numpy as np

In [35]:
coeffs = np.array([[2,6],[5,3]])
values = np.array([[6] ,[-9]])

In [36]:
values.shape

(2, 1)

In [37]:
coeff_matrix = np.matrix(coeffs)
values_matrix  = np.matrix(values)

In [12]:
coeff_matrix
values_matrix

matrix([[ 6],
        [-9]])

In [14]:
coeffInverse = coeff_matrix.getI()

In [38]:
ans = np.dot(coeffInverse,values_matrix)

In [39]:
ans

matrix([[-3.],
        [ 2.]])

In [40]:
ans[0,0]

-3.0

In [42]:
ans[1,0]

2.0

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
coeffs.transpose()

array([[2, 5],
       [6, 3]])